FROM byliuyang/go-builder:latest

# Install and verify dependencies
COPY backend/go.mod backend/go.sum ./
RUN go mod download && \
	go mod verify

COPY . .

ARG CODECOV_TOKEN

ENV CODECOV_TOKEN=${CODECOV_TOKEN}

CMD ["./scripts/report-coverage"]