FROM golang:1.13.0-alpine

WORKDIR /app

# Install tools
RUN apk add --no-cache git
RUN apk add --no-cache bash
RUN apk add --no-cache gcc
RUN apk add --no-cache libc-dev
RUN apk add --no-cache curl

# Install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Verify dependencies
RUN go mod verify

COPY . .

ARG CODECOV_TOKEN

ENV CODECOV_TOKEN=${CODECOV_TOKEN}

CMD ["./bin/code-coverage"]