// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: app/adapter/grpcapi/proto/metatag.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetOGTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alias string `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
}

func (x *GetOGTagsRequest) Reset() {
	*x = GetOGTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_adapter_grpcapi_proto_metatag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOGTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOGTagsRequest) ProtoMessage() {}

func (x *GetOGTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_adapter_grpcapi_proto_metatag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOGTagsRequest.ProtoReflect.Descriptor instead.
func (*GetOGTagsRequest) Descriptor() ([]byte, []int) {
	return file_app_adapter_grpcapi_proto_metatag_proto_rawDescGZIP(), []int{0}
}

func (x *GetOGTagsRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type GetOGTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl    string `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *GetOGTagsResponse) Reset() {
	*x = GetOGTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_adapter_grpcapi_proto_metatag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOGTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOGTagsResponse) ProtoMessage() {}

func (x *GetOGTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_adapter_grpcapi_proto_metatag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOGTagsResponse.ProtoReflect.Descriptor instead.
func (*GetOGTagsResponse) Descriptor() ([]byte, []int) {
	return file_app_adapter_grpcapi_proto_metatag_proto_rawDescGZIP(), []int{1}
}

func (x *GetOGTagsResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetOGTagsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetOGTagsResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type GetTwitterTagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alias string `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
}

func (x *GetTwitterTagsRequest) Reset() {
	*x = GetTwitterTagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_adapter_grpcapi_proto_metatag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTwitterTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTwitterTagsRequest) ProtoMessage() {}

func (x *GetTwitterTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_adapter_grpcapi_proto_metatag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTwitterTagsRequest.ProtoReflect.Descriptor instead.
func (*GetTwitterTagsRequest) Descriptor() ([]byte, []int) {
	return file_app_adapter_grpcapi_proto_metatag_proto_rawDescGZIP(), []int{2}
}

func (x *GetTwitterTagsRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type GetTwitterTagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl    string `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *GetTwitterTagsResponse) Reset() {
	*x = GetTwitterTagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_adapter_grpcapi_proto_metatag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTwitterTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTwitterTagsResponse) ProtoMessage() {}

func (x *GetTwitterTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_adapter_grpcapi_proto_metatag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTwitterTagsResponse.ProtoReflect.Descriptor instead.
func (*GetTwitterTagsResponse) Descriptor() ([]byte, []int) {
	return file_app_adapter_grpcapi_proto_metatag_proto_rawDescGZIP(), []int{3}
}

func (x *GetTwitterTagsResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetTwitterTagsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTwitterTagsResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_app_adapter_grpcapi_proto_metatag_proto protoreflect.FileDescriptor

var file_app_adapter_grpcapi_proto_metatag_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x61,
	0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4f, 0x47, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x68, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x4f, 0x47, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x55, 0x72, 0x6c, 0x22, 0x2d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x77, 0x69, 0x74, 0x74,
	0x65, 0x72, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c,
	0x69, 0x61, 0x73, 0x22, 0x6d, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x54, 0x77, 0x69, 0x74, 0x74, 0x65,
	0x72, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55,
	0x72, 0x6c, 0x32, 0xa3, 0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x61, 0x54, 0x61, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4f, 0x47, 0x54, 0x61,
	0x67, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x47,
	0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x47, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x77,
	0x69, 0x74, 0x74, 0x65, 0x72, 0x54, 0x61, 0x67, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x54, 0x61, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_adapter_grpcapi_proto_metatag_proto_rawDescOnce sync.Once
	file_app_adapter_grpcapi_proto_metatag_proto_rawDescData = file_app_adapter_grpcapi_proto_metatag_proto_rawDesc
)

func file_app_adapter_grpcapi_proto_metatag_proto_rawDescGZIP() []byte {
	file_app_adapter_grpcapi_proto_metatag_proto_rawDescOnce.Do(func() {
		file_app_adapter_grpcapi_proto_metatag_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_adapter_grpcapi_proto_metatag_proto_rawDescData)
	})
	return file_app_adapter_grpcapi_proto_metatag_proto_rawDescData
}

var file_app_adapter_grpcapi_proto_metatag_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_adapter_grpcapi_proto_metatag_proto_goTypes = []interface{}{
	(*GetOGTagsRequest)(nil),       // 0: proto.GetOGTagsRequest
	(*GetOGTagsResponse)(nil),      // 1: proto.GetOGTagsResponse
	(*GetTwitterTagsRequest)(nil),  // 2: proto.GetTwitterTagsRequest
	(*GetTwitterTagsResponse)(nil), // 3: proto.GetTwitterTagsResponse
}
var file_app_adapter_grpcapi_proto_metatag_proto_depIdxs = []int32{
	0, // 0: proto.MetaTagService.GetOGTags:input_type -> proto.GetOGTagsRequest
	2, // 1: proto.MetaTagService.GetTwitterTags:input_type -> proto.GetTwitterTagsRequest
	1, // 2: proto.MetaTagService.GetOGTags:output_type -> proto.GetOGTagsResponse
	3, // 3: proto.MetaTagService.GetTwitterTags:output_type -> proto.GetTwitterTagsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_adapter_grpcapi_proto_metatag_proto_init() }
func file_app_adapter_grpcapi_proto_metatag_proto_init() {
	if File_app_adapter_grpcapi_proto_metatag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_adapter_grpcapi_proto_metatag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOGTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_adapter_grpcapi_proto_metatag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOGTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_adapter_grpcapi_proto_metatag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTwitterTagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_adapter_grpcapi_proto_metatag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTwitterTagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_adapter_grpcapi_proto_metatag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_adapter_grpcapi_proto_metatag_proto_goTypes,
		DependencyIndexes: file_app_adapter_grpcapi_proto_metatag_proto_depIdxs,
		MessageInfos:      file_app_adapter_grpcapi_proto_metatag_proto_msgTypes,
	}.Build()
	File_app_adapter_grpcapi_proto_metatag_proto = out.File
	file_app_adapter_grpcapi_proto_metatag_proto_rawDesc = nil
	file_app_adapter_grpcapi_proto_metatag_proto_goTypes = nil
	file_app_adapter_grpcapi_proto_metatag_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MetaTagServiceClient is the client API for MetaTagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetaTagServiceClient interface {
	GetOGTags(ctx context.Context, in *GetOGTagsRequest, opts ...grpc.CallOption) (*GetOGTagsResponse, error)
	GetTwitterTags(ctx context.Context, in *GetTwitterTagsRequest, opts ...grpc.CallOption) (*GetTwitterTagsResponse, error)
}

type metaTagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaTagServiceClient(cc grpc.ClientConnInterface) MetaTagServiceClient {
	return &metaTagServiceClient{cc}
}

func (c *metaTagServiceClient) GetOGTags(ctx context.Context, in *GetOGTagsRequest, opts ...grpc.CallOption) (*GetOGTagsResponse, error) {
	out := new(GetOGTagsResponse)
	err := c.cc.Invoke(ctx, "/proto.MetaTagService/GetOGTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaTagServiceClient) GetTwitterTags(ctx context.Context, in *GetTwitterTagsRequest, opts ...grpc.CallOption) (*GetTwitterTagsResponse, error) {
	out := new(GetTwitterTagsResponse)
	err := c.cc.Invoke(ctx, "/proto.MetaTagService/GetTwitterTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaTagServiceServer is the server API for MetaTagService service.
type MetaTagServiceServer interface {
	GetOGTags(context.Context, *GetOGTagsRequest) (*GetOGTagsResponse, error)
	GetTwitterTags(context.Context, *GetTwitterTagsRequest) (*GetTwitterTagsResponse, error)
}

// UnimplementedMetaTagServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMetaTagServiceServer struct {
}

func (*UnimplementedMetaTagServiceServer) GetOGTags(context.Context, *GetOGTagsRequest) (*GetOGTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOGTags not implemented")
}
func (*UnimplementedMetaTagServiceServer) GetTwitterTags(context.Context, *GetTwitterTagsRequest) (*GetTwitterTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTwitterTags not implemented")
}

func RegisterMetaTagServiceServer(s *grpc.Server, srv MetaTagServiceServer) {
	s.RegisterService(&_MetaTagService_serviceDesc, srv)
}

func _MetaTagService_GetOGTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOGTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaTagServiceServer).GetOGTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MetaTagService/GetOGTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaTagServiceServer).GetOGTags(ctx, req.(*GetOGTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaTagService_GetTwitterTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTwitterTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaTagServiceServer).GetTwitterTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MetaTagService/GetTwitterTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaTagServiceServer).GetTwitterTags(ctx, req.(*GetTwitterTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetaTagService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MetaTagService",
	HandlerType: (*MetaTagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOGTags",
			Handler:    _MetaTagService_GetOGTags_Handler,
		},
		{
			MethodName: "GetTwitterTags",
			Handler:    _MetaTagService_GetTwitterTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/adapter/grpcapi/proto/metatag.proto",
}
