// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dep

import (
	"tinyURL/app"
	"tinyURL/modern"
)

// Injectors from wire.go:

func InitGraphQlService(name string, graphqlPath modern.GraphQlPath) modern.Service {
	logger := modern.NewLocalLogger()
	tracer := modern.NewLocalTracer()
	graphQlApi := app.NewGraphQlApi(logger, tracer)
	server := modern.NewGraphGophers(graphqlPath, logger, tracer, graphQlApi)
	service := modern.NewService(name, server, logger)
	return service
}

func InitRoutingService(name string) modern.Service {
	logger := modern.NewLocalLogger()
	tracer := modern.NewLocalTracer()
	routes := app.NewRoutes(logger, tracer)
	server := modern.NewGorillaMux(logger, tracer, routes)
	service := modern.NewService(name, server, logger)
	return service
}
