// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dep

import (
	"database/sql"
	"short/app/adapter/account"
	"short/app/adapter/graphql"
	"short/app/adapter/repo"
	"short/app/usecase/keygen"
	"short/app/usecase/requester"
	"short/app/usecase/url"
	new2 "short/dep/new"
	"short/modern/mdhttp"
	"short/modern/mdlogger"
	"short/modern/mdrequest"
	"short/modern/mdrouting"
	"short/modern/mdservice"
	"short/modern/mdtimer"
	"short/modern/mdtracer"
)

// Injectors from wire.go:

func InitGraphQlService(name string, db *sql.DB, graphqlPath new2.GraphQlPath, secret new2.ReCaptchaSecret) mdservice.Service {
	logger := mdlogger.NewLocal()
	tracer := mdtracer.NewLocal()
	repoUrl := repo.NewUrlSql(db)
	retriever := url.NewRetrieverPersist(repoUrl)
	keyGenerator := keygen.NewInMemory()
	creator := url.NewCreatorPersist(repoUrl, keyGenerator)
	client := mdhttp.NewClient()
	httpRequest := mdrequest.NewHttp(client)
	reCaptcha := new2.ReCaptchaService(httpRequest, secret)
	verifier := requester.NewVerifier(reCaptcha)
	graphQlApi := graphql.NewShort(logger, tracer, retriever, creator, verifier)
	server := new2.GraphGophers(graphqlPath, logger, tracer, graphQlApi)
	service := mdservice.New(name, server, logger)
	return service
}

func InitRoutingService(name string, db *sql.DB, wwwRoot new2.WwwRoot, githubClientId new2.GithubClientId, githubClientSecret new2.GithubClientSecret, jwtSecret new2.JwtSecret) mdservice.Service {
	logger := mdlogger.NewLocal()
	tracer := mdtracer.NewLocal()
	timer := mdtimer.NewTimer()
	repoUrl := repo.NewUrlSql(db)
	retriever := url.NewRetrieverPersist(repoUrl)
	client := mdhttp.NewClient()
	httpRequest := mdrequest.NewHttp(client)
	github := new2.GithubOAuth(httpRequest, githubClientId, githubClientSecret)
	graphQlRequest := mdrequest.NewGraphQl(httpRequest)
	accountGithub := account.NewGithub(graphQlRequest)
	cryptoTokenizer := new2.JwtGo(jwtSecret)
	authenticator := new2.Authenticator(cryptoTokenizer, timer)
	v := new2.ShortRoutes(logger, tracer, wwwRoot, timer, retriever, github, accountGithub, authenticator)
	server := mdrouting.NewBuiltIn(logger, tracer, v)
	service := mdservice.New(name, server, logger)
	return service
}
